import { initializeApp } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js";
import { getFirestore, doc, getDoc, setDoc, onSnapshot } from "https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js";

const firebaseConfig={apiKey:"AIzaSyDzpJvxluGEoBDLXX9MioPnp7UpJ4ofJ2A",authDomain:"ne-wallet-web.firebaseapp.com",projectId:"ne-wallet-web",storageBucket:"ne-wallet-web.firebasestorage.app",messagingSenderId:"292475418110",appId:"1:292475418110:web:2c4339454587c578433caf",measurementId:"G-M8NWL4F77L"};
const app=initializeApp(firebaseConfig), db=getFirestore(app), walletRef=doc(db,"wallets","shared-ne-wallet");
let state=null, applyingRemote=false;
const $=id=>document.getElementById(id);
const money=n=>new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY'}).format(Number(n)||0);
const net=u=>(Number(u?.cash)||0)+(Number(u?.investment)||0)-(Number(u?.debt)||0);
const fmtDate=s=>{try{return new Intl.DateTimeFormat('tr-TR',{day:'numeric',month:'short'}).format(new Date(s+'T12:00:00'))}catch{return s||''}};
function txt(id,v){const el=$(id);if(el)el.textContent=v}
async function persist(){localStorage.setItem('ne-wallet-state',JSON.stringify(state));if(applyingRemote)return;try{await setDoc(walletRef,{...state,updatedAt:new Date().toISOString()})}catch(e){console.warn('Firebase yazma:',e)}}
function render(){if(!state?.balances)return;const n=state.balances.nisu||{},e=state.balances.erol||{};txt('nisuNet',money(net(n)));txt('nisuNetCard',money(net(n)));txt('erolNet',money(net(e)));txt('combined',money(net(n)+net(e)));txt('nisuCash',money(n.cash));txt('nisuInv',money(n.investment));txt('nisuDebt',money(n.debt));txt('erolCash',money(e.cash));txt('erolInv',money(e.investment));txt('erolDebt',money(e.debt));renderAccounts();renderTx()}
function renderAccounts(){const box=$('accounts');if(!box)return;box.innerHTML='';(state.accounts||[]).filter(a=>a.owner==='nisu').forEach(a=>{const d=document.createElement('div');d.className='account';d.innerHTML=`<span>${a.name}</span><b>${money(a.balance)}</b><div class="account-actions">düzenle &nbsp; sil</div>`;box.appendChild(d)})}
function renderTx(){const box=$('transactions');if(!box)return;box.innerHTML='';[...(state.transactions||[])].sort((a,b)=>(b.date||'').localeCompare(a.date||'')).forEach(t=>{const d=document.createElement('div');d.className='tx';d.innerHTML=`<div class="emoji">${state.categoryEmoji?.[t.category]||'✨'}</div><div><b>${t.merchant||''}</b><small>${t.owner==='erol'?'Erol':'Nisu'} · ${t.category||'diğer'} · ${fmtDate(t.date)} · ${t.account||''}</small></div><div class="amount">-${money(t.amount)}</div>`;box.appendChild(d)})}
async function load(){const base=await fetch('./data.json',{cache:'no-store'}).then(r=>r.json());let local=null;try{local=JSON.parse(localStorage.getItem('ne-wallet-state')||'null')}catch{}state=local||base;render();try{const snap=await getDoc(walletRef);if(snap.exists()){applyingRemote=true;state=snap.data();localStorage.setItem('ne-wallet-state',JSON.stringify(state));applyingRemote=false;render()}else{await setDoc(walletRef,{...state,updatedAt:new Date().toISOString()})}onSnapshot(walletRef,s=>{if(!s.exists())return;applyingRemote=true;state=s.data();localStorage.setItem('ne-wallet-state',JSON.stringify(state));applyingRemote=false;render()},e=>console.warn('Firebase dinleme:',e))}catch(e){console.warn('Yerel mod:',e)}}
function openModal(){const el=$('modal');if(el)el.classList.add('open')}function closeModal(){const el=$('modal');if(el)el.classList.remove('open')}
async function addTx(ev){ev.preventDefault();const f=new FormData(ev.target);state.transactions=state.transactions||[];state.transactions.push({id:Date.now(),owner:f.get('owner'),merchant:f.get('merchant'),account:f.get('account'),category:f.get('category'),date:f.get('date'),amount:Number(f.get('amount'))});await persist();render();closeModal();ev.target.reset()}
async function editDebt(user){const cur=state?.balances?.[user]?.debt??0;const v=prompt(`${user==='nisu'?'Nisu':'Erol'} toplam borcu`,String(cur).replace('.',','));if(v===null)return;const n=Number(String(v).replace(/\./g,'').replace(',','.'));if(!Number.isFinite(n))return alert('Geçerli bir tutar gir.');state.balances[user].debt=n;await persist();render()}
window.openModal=openModal;window.closeModal=closeModal;window.addTx=addTx;window.editDebt=editDebt;window.addEventListener('DOMContentLoaded',load);
